# Generated by Django 4.0.5 on 2022-06-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='adress',
            new_name='address',
        ),
    ]
